version: '3.4'

services: 
    db:
        image: mysql
        container_name: zpt-db
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - zptdb:/var/lib/mysql:delegated
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_USERPASS}"
        ports:
            - "33060:3306"
        networks:
            default:
                ipv4_address: 172.25.0.10        

    api:
        container_name: zpt-php
        volumes: 
            - ./api:/var/www/html:delegated
        build: 
            context: .
            dockerfile: ./docker/php/Dockerfile
        depends_on:
            - "db"
        networks:
            default:
                ipv4_address: 172.25.0.2
    
    webserver:
        container_name: zpt-ws
        volumes: 
            - ./api:/var/www/html:delegated
        build: 
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        depends_on:
            - "api"
        ports:
            - "8085:80"
        networks:
            default:
                ipv4_address: 172.25.0.3

networks:
    default:
        external: true
        name: zpt-network
    
volumes:
    zptdb: